# ----------------- DB -----------------
spring.datasource.url=jdbc:mysql://localhost:3306/animal_finder?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ----------------- Upload -----------------
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=./uploads

# ----------------- Mail (Gmail SMTP) -----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mvmluis@gmail.com
spring.mail.password=tccqblbjthlzyvys
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# "From" e Reply-To (recomendado: o próprio Gmail)
app.mail.from=Pet Alerta <mvmluis@gmail.com>
app.mail.replyTo=mvmluis@gmail.com

paypal.baseUrl=https://api-m.sandbox.paypal.com
paypal.clientId=AegcHnE-q3wS_gI1L5mH5io0Fcqh537HbuA6QT95hq4Bnw9ikZi8sswifw-iQsAammu6QxmXwQIjSrkc
paypal.clientSecret=EMqoyufX90PRUoqbYdtyyMLdv-mnd0UxKrbvZDacRzEV-EHDiyun1bOO2GoVunz8nV_clSTVSx0KbCJQ
paypal.returnUrl=http://localhost:8080/donations/money/return
paypal.cancelUrl=http://localhost:8080/donations/money/cancel
paypal.currency=EUR

spring.security.oauth2.client.registration.google.client-id=993433523320-pkj7334n221k93cbo0mglb5mcojefat6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# uploads chat (fora do classpath)
app.chat.upload-dir=./uploads/chat
chat.attachments.max-file-size=5242880
chat.attachments.allowed-types=image/jpeg,image/png,image/webp,application/pdf

# ----------------- App -----------------
spring.jackson.time-zone=Europe/Lisbon
